on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    - name: Create comment
      uses: peter-evans/create-or-update-comment@v2
      with:
        issue-number: 5
        body: |
          The PR increasing the hash of submodule is merged.
          - You can alter the submodule hash to **XXXXCCCCC** :sparkles:
          - Created by [create-or-update-comment][1]

          [1]: https://github.com/peter-evans/create-or-update-comment
        reactions: '+1'