name: Find Submodule PR Train 🚀
run-name: ${{ github.actor }} is testing out GitHub Actions 
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Explore Submodules
        run: |
          python3 train.py
      - run: echo "This job's status is ${{ job.status }}."