on:
  workflow_dispatch:
    inputs:
      pr:
        description: 'PR number'
        required: true 
        type: string
      body:
        description: 'The markdown supported body'
        required: true 
        type: string

jobs:
  post-comment:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    - name: Create comment
      uses: peter-evans/create-or-update-comment@v2
      with:
        issue-number: ${{ inputs.pr }} 
        body: ${{ inputs.body }}